name: Enaro Integration
description: Installiert die Enaro Integration fuer Einkaufslisten und automatische Enaro-Aufgaben aus Home Assistant
version: "0.2.2"
slug: enaro_shopping
init: false
startup: once
boot: manual
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
homeassistant_api: true
panel_icon: mdi:clipboard-check-outline
map:
  - config:rw
options:
  log_level: info
  restart_homeassistant: false
schema:
  log_level: list(debug|info|warning|error|critical)
  restart_homeassistant: bool
